[versions]
agp = "9.0.0"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"
androidx-activity = "1.12.2"
androidx-appcompat = "1.7.1"
composeMultiplatform = "1.10.0"
junit = "4.13.2"
kotlin = "2.3.0"
kotlinx-coroutines = "1.10.2"
ktor = "3.3.3"
coil = "3.3.0"
material = "1.13.0"

[libraries]
junit = { module = "junit:junit", version.ref = "junit" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }

jetbrains-compose-runtime = "org.jetbrains.compose.runtime:runtime:1.10.0"
jetbrains-compose-foundation = "org.jetbrains.compose.foundation:foundation:1.10.0"
jetbrains-compose-material3 = "org.jetbrains.compose.material3:material3:1.10.0-alpha05"
jetbrains-compose-materialIconsExtended = "org.jetbrains.compose.material:material-icons-extended:1.7.3"
jetbrains-compose-navigationevent = "org.jetbrains.androidx.navigationevent:navigationevent-compose:1.0.0"
jetbrains-compose-ui = "org.jetbrains.compose.ui:ui:1.10.0"
jetbrains-compose-resources = "org.jetbrains.compose.components:components-resources:1.10.0"
jetbrains-compose-preview = "org.jetbrains.compose.ui:ui-tooling-preview:1.10.0"
jetbrains-compose-tooling = "org.jetbrains.compose.ui:ui-tooling:1.10.0"

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }

kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
leakcanary-android = "com.squareup.leakcanary:leakcanary-android:2.14"
kermit = "co.touchlab:kermit:2.0.8"
logback = "ch.qos.logback:logback-classic:1.5.24"

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-encoding = { module = "io.ktor:ktor-client-encoding", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-ktor3 = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }

[bundles]
ktor-client = [
    "ktor-client-core",
    "ktor-client-cio",
    "ktor-client-serialization",
    "ktor-client-logging",
    "ktor-client-content-negotiation",
    "ktor-client-encoding",
    "ktor-serialization-kotlinx-json",
]

coil = [
    "coil-compose",
    "coil-ktor3",
]

[plugins]
ksp = "com.google.devtools.ksp:2.3.4"
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
androidMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }